### ISSUE TITLE
Character duplication bug

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik-15#193]
When duplicate a character already rigged some functions doesn't work. For example the Clockwise. In my original comp it works but in my duplicate character it doesn't.

**Comment by Nico-Duduf** [comment]
can't reproduce bug,
can anyone send me an example project where the duplication does not work?

**Comment by cetmarques** [comment]
[characterA_rig_02.zip](https://github.com/Duduf-dev/Duik/files/142888/characterA_rig_02.zip)

Ok, I'm having this same problem you're describing. Everything runs well, but as soon as I duplicate my compositions I'm not able to uncheck clockwise function. Well, I can do that, but it doesn't work.
It would be wonderful if you could solve this bug.
Thanks!

**Comment by Nico-Duduf** [comment]
Thanks, I'll have a look at that!

**Comment by danbroken** [comment]
Well, I have a tip about what's happening. When we duplicate a composition, the effect with clockwise option remain being controlled by the effect from original control ik. A way to test is duplicate and animate clockwise in original composition. So you will see the duplicated composition being animated too at the same frame point.  Sorry my bad english.

**Comment by Nico-Duduf** [comment]
Thanks for your feedback, I'll fix this as soon as possible!
