### ISSUE TITLE
Updating imported instance from original rigging changes (workaround)

### ISSUE THREAD

**Issue by JuanGarces** [Rainbox-dev/Duik-15#204]
Hi, I'm new and I didn't find a better solution when I make changes in the original rigging and I want my animation to be updated with them (like adding a new layer or modifying the puppet mesh). Please, tell me if there is a easier way instead of what I did:
1. Deleted the duplicated rigging.
2. Imported again the original rigging with the exact name of the old instance.
3. Deleted all the new duplicated controllers.

Is there a better way to do it? Thanks in advance.

**Comment by Nico-Duduf** [comment]
Thanks for your feedback, I'll have a look at this. I think there is indeed something to be scripted here

**Comment by JuanGarces** [comment]
Yes, I also thought that scripting would be applicable but that is far away from my skills. Please, let me know if you make it happen.

**Comment by JuanGarces** [comment]
I've just found a problem with my procedure:
When I change a value to a the controller slider in the original rigging, it would not be in the new imported instance because I have to delete this controller to keep my animations in the old ones.

**Comment by Nico-Duduf** [comment]
I'm thinking of several ways to update a rig after it has been animated.
Another way would be to save the animation to an external file, deleting the old rig, importing the new one, and then reloading the animation onto it.
This way, values which have been changed on the controllers of the new rig would be kept.

Maybe you can test that using the copy/paste animation tool of Duik ; copy the animation before deleteing and reimporting the rig, then just hit the paste button.
You'll have to make sure you keep the controllers' names.

**Comment by Nico-Duduf** [comment]
(or you could simply follow your procedure, but instead of deleting the new controllers, copy and paste the animation from the old controllers to the new ones, and delete the old controllers)

**Comment by JuanGarces** [comment]
It almost worked. The animation itself is fine but it didn't copy some "loopout" expressions I had. I don't know if I did something wrong.

**Comment by Nico-Duduf** [comment]
No you didn't, the copy/paste animation tool does not copy expressions. But that's something it should optionnally do, I'll add this to the next version!
The same tool will be able to save animations in external files, I think it could be very useful.

**Comment by JuanGarces** [comment]
I'm looking forward to it. Thanks!
