### ISSUE TITLE
Error at line 8

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik-15#233]
"Unable to execute file at line 8. Null is not an object"

when launching Duik

(Windows 10, AE CC 2015)

**Comment by eZioPan** [comment]
Not show with AE CC 2015.2: Version 17.7.1.6 , Windows7 , Duik15.09

**Comment by Nico-Duduf** [comment]
can't find what may be wrong in Duik, need more feedback from other users.

I think it could be an incorrect installation which causes this.

**Comment by kevinmasson** [comment]
Is this still happening ?

**Comment by kevinmasson** [comment]
AE CC 2015 Version 13.6.1 Windows 10 Duik 15.11, not happening !
