### ISSUE TITLE
Lottie & bodymovin integration

### ISSUE THREAD

**Issue by fdnhkj** [Rainbox-dev/Duik-15#299]
Hello!

Did you investigate the possibility of using [Lottie](https://github.com/airbnb/lottie-ios) and [bodymovin](https://github.com/bodymovin/bodymovin) with AE animations containing Duik effects ?

Thanks!

**Comment by Nico-Duduf** [comment]
I've heard of people using bodymovin with Duik, and it seems to work in most cases!
I didn't have time to investigate this myself...

**Comment by oktomus** [comment]
If you can provide an animation made with duik with enough complexity to be tested, I can test bodymovin and see what's working and what's not

**Comment by Nico-Duduf** [comment]
Yes, let's do that. Il create an AE project with a comp for each rigging tool, then a more complex animated character

**Comment by nerdmanship** [comment]
Any updates on Lottie integration?
Thank you

**Comment by Nico-Duduf** [comment]
Not yet, I wish days lasted 40hours, at least :'(

BUT I read about people succesfully using Duik & Bodymovin, just needs to convert some expressions to keyframes sometimes

**Comment by nerdmanship** [comment]
Thank you, Nico!

No stress, enjoy the ride! Big fan of your stuff.

Yes, bodymovin works excellent in browser. Lottie with react native is far more restricted tho.
