### ISSUE TITLE
Structures: Modify selection

### ISSUE THREAD

**Issue by oktomus** [Rainbox-dev/Duik-15#304]
That would be great to modify the size/color/opacity of multiple bones (have all options in the same area). And for the size, we can't change multiple effect attribute at the same time so that could fix the problem.

That could be done by adding a button modify next to create.

**Comment by Nico-Duduf** [comment]
color and opacity can already be easily modified inside After Effects ;

But a "bone editor" (a bit like the one which exists in 3DS Max, and its "bone edit mode") could be great

With the option to color the bones with a nice ramp from root to end 😄 (which could be used by default)

**Comment by Nico-Duduf** [comment]
Bone editor:

- [ ] color
- [ ] color ramp
- [ ] opacity
- [ ] size
- [ ] bone edit mode (temporarily unparent and deactivate expressions in transform properties)
- [ ] option to work on selection or all bones

**Comment by oktomus** [comment]
So cool the color ramp :0 do you want to add the editor right in the same window ?

**Comment by Nico-Duduf** [comment]
I think at first it's better to develop this in a stand alone script, like I did for the current Duik16 bones and connector, it will be easier to develop the UI, and update it when adding new features progressively

This way, designing the final UI of Duik16 will be easier, seeing what has to be included; and including all those features from those "testing" scripts should not be hard.

**Comment by Nico-Duduf** [comment]
As there are a lot of controls (I just added some), I think it can be good to divide the new bones tool in two tabs: create mode and edit mode;
this will be the edit mode, and the already existing bones script would be the create mode (with IK and all other rigging stuff)

**Comment by oktomus** [comment]
The tabs is a great idea. Let's do this.

**Comment by Nico-Duduf** [comment]
I've begun this in the new UI of Duik16, works well. Still have to add some properties and find a way to keep the UI as clear as possible :)
