### ISSUE TITLE
Duik 16 Connector: List connection on select layers/properties

### ISSUE THREAD

**Issue by oktomus** [Rainbox-dev/Duik-15#306]

**Comment by Nico-Duduf** [comment]
Good idea
will have to add the informations in the layer's comments, to be quicker than checking all the expressions.
I already add some infos in the comments when creating IK, it can be done with the same template

**Comment by oktomus** [comment]
Nice! In don't know if it's better to select the related properties, or to display a list in the UI ?

**Comment by Nico-Duduf** [comment]
We have to do this in the UI: the properties can be in several compositions at once ;)

**Comment by oktomus** [comment]
Right ! ^^
