### ISSUE TITLE
IK problem misplaced parts

### ISSUE THREAD

**Issue by myehsan** [Rainbox-dev/Duik-15#308]
hey , i'm trying to rig a hand and when i press IK the parts go crazy and misplace!
![dxgfergtfxghdfghgbser](https://cloud.githubusercontent.com/assets/27468473/25032104/ca796098-20e6-11e7-91c1-e363cfbac7ed.JPG)
i was hoping if it will get fixed in this new update you released but it didn't
i'm using Windows 10 and Adobe AE CC 2017 (14.0.0.207 )
i tried AI and PSD , but both of them had the same issue

**Comment by Beth119** [comment]
I'm having the same problem. Have you found a solution? :/

**Comment by myehsan** [comment]
no i didn't . and nobody even looked at this issue!
one of my friends recommended me to use older versions of AE to solve this , but i didn't try it yet

**Comment by oktomus** [comment]
Hello @myehsan, thanks for your feedback, but can you give us more details ? The best would be to record a video of the issue happening.
