### ISSUE TITLE
data exportation from Duik

### ISSUE THREAD

**Issue by Nico-Duduf** [Rainbox-dev/Duik-15#63]
export animation and rig data from After Effects, to be reused in games engines, AS3...

- animation
- sprites
- controllers
- rig (IK and other expressions from Duik)
- option to automatically convert all expressions or all but supported rig to keyframes
- option to automatically delete all rig (including parenting, or not), replaced by one keyframe per frame

**ANIMATION** (15.5)
- [x] JSON Export #323 
- [x] JSON Import  #316 
- [x] XML Export #317 
- [x] XML Import #318 

**Rig** (16 with the new bone structures)
- [ ] JSON Export #319 
- [ ] JSON Import  #320 
- [ ] XML Export #321 
- [ ] XML Import #322

**Comment by Quentie** [comment]
Please consider a well known fileformat that already has runtimes for several gameengines if possible. E.g.: spine and dragonbones come to mind. Even though the official spine runtimes do require your users to also buy a spine license there are also a lot of third party runtimes available that are not based on the official runtimes and do not have these restrictions. This would be awesome;)

**Comment by Nico-Duduf** [comment]
At first, we're going to use very open formats like JSON and XML, but without any runtime for game engines (it means developpers will have to develop their own)

Once this is done, we'll see if it's possible to develop an export for dragonbones. But this is unlikely, as dragobones and spine have a very different features than Duik and After Effects...
